Fix mteam fail to add and easily unaviliable issue
Prowlarr/Prowlarr pull request #1121
Opened 2022-09-13 07:08 UTC by luckyboy

#### Database Migration
NO

#### Description
This PR fix mteam fail to add and easily unavailable issue. 
The site mteam has overloading detection which block access in 120s. So, there are still improvements to do to avoid 
too many access in short period of time.

#### Screenshot (if UI related)

#### Todos
Http request flow need to improve for decreasing number of requests for login or searching.

#### Issues Fixed or Closed by this PR

* Fixes #1061

2022-09-13 11:40 UTC, bakerboy448 requested changes
- why the build props changes? That seems unrelated to m team?   M1 support already exists and was added with https://github.com/Prowlarr/Prowlarr/commit/c35e257a82dcacdc282124d1fd7d8fefc7cba61f
- What is the purpose of `CFPCheck` and why is it always true?
- What is this new "portal" functionality for Cardigann and how is it to be used?
- Looks like login portal can just leverage the existing login test logic instead, no?
- non-backwards compatible Cardigann changes like this require a Cardigann version bump, a resulting new schema on the definitions, and the corresponding new definition
- believe Mteam was working and fixed with https://github.com/Prowlarr/Prowlarr/pull/1120

2022-09-14 07:34 UTC, luckyboy commented
> * why the build props changes? That seems unrelated to m team?   M1 support already exists and was added with [c35e257](https://github.com/Prowlarr/Prowlarr/commit/c35e257a82dcacdc282124d1fd7d8fefc7cba61f)
   
RE:Sorry, this change does not related to mteam, it's a fix for VisualStudio on M1 Mac(RuntimeIdentifier is set to osx-x64 which cause fail to launch program from VS), just ignore it.
> * What is the purpose of `CFPCheck` and why is it always true?
  
 RE:Request to mteam without UserAgent (login flow) will receive a page not found response(html), but CloudFlareDetectionService.IsCloudflareProtected can't handle this scenary well, so, CFPCkeck is purposed to skip this step 
with mteamtp  definition change, and thus make sure no side effect to other indexers.
> * What is this new "portal" functionality for Cardigann and how is it to be used?
   
RE:Portal function is also purposed to fix mteam login checking logic. The original code CardigannRequestGenerator.CheckIfLoginIsNeeded is not strong enough to return a correct login status, which will cause re-login for most searching request, but unfortunately mteam has login security check, too many login will cause account locked, finally the indexer(mteam) will show unavailable. Also CardigannParser.ParseResponse will receive an access blocking page(loading is high) from mteam if too many request in a short peroid of time, so the error handling should also be improved for avoiding return a confused exception in the log file.
> * Looks like login portal can just leverage the existing login test logic instead, no?
    
RE:The reason why login portal is introduced is still related to the login status checking logic. The existing logic check the login status by searching logout.php, but there are pages not contain logout.php(for example the access blocking page), this  will cause re-login.
> * non-backwards compatible Cardigann changes like this require a Cardigann version bump, a resulting new schema on the definitions, and the corresponding new definition
    
RE:There no backwards compatible issue with those code, because these code changes and mteam definition changes just work for mteam only, also there is no side effect without mteam definition change.
> * believe Mteam was working and fixed with #1120
    
RE:#120 just fixed login issue, but mteam indexer still can't work due to lack of proper error handling mentioned above.

2022-09-14 13:01 UTC, bakerboy448 commented
If the new definition works without error on nightly (other than obviously not working for the known issues) then you don't need to bump Cardigann versions.  If it does - which it looks rather likely. Then you will need to bump the Cardigann version and handle the associated schema update in the indexer repo.

M1 Mac VS build fixes should ideally be in its own branch and ported to all the \*arrs as well


How exactly is the cloudflare protection detection causing issues?

This tracker was already confirmed to be fixed by other users when the redirect logic change was made. Do you have trace logs of it failing on the latest nightly build?

2022-09-15 07:51 UTC, luckyboy commented
> If the new definition works without error on nightly (other than obviously not working for the known issues) then you don't need to bump Cardigann versions. If it does - which it looks rather likely. Then you will need to bump the Cardigann version and handle the associated schema update in the indexer repo.
> 
> Pretty sure it'll need the bump.
> 
> M1 Mac VS build fixes should ideally be in its own branch and ported to all the *arrs as well
> 
> How exactly is the cloudflare protection detection causing issues?
> 
> This tracker was already confirmed to be fixed and working by other users when the redirect logic change was made. Do you have trace logs of it failing on the latest nightly build with Flaresolverr 2.2.7 (their latest release) and the FS proxy enabled for this tracker?

Here is the test log from lasted nightly build with Flaresolverr 2.2.7, still failed after login.
https://pastebin.com/iadxbGJ9

By the way, could you please give me an example commit of bump Cardigann versions.?

2022-09-15 12:16 UTC, bakerboy448 commented
Info logs are not trace logs

2022-09-19 08:03 UTC, luckyboy commented
Below is trace and debug files
[prowlarr.debug.txt](https://github.com/Prowlarr/Prowlarr/files/9597088/prowlarr.debug.txt)
[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/9597090/prowlarr.trace.txt)

2022-09-19 08:04 UTC, luckyboy commented
> Info logs are not trace logs
> 
> Indexers Repo has the versions linked to their prowlarr commits IIRC
Below is debug and trace files when failure happen
[prowlarr.trace.txt](https://github.com/Prowlarr/Prowlarr/files/9597099/prowlarr.trace.txt)
[prowlarr.debug.txt](https://github.com/Prowlarr/Prowlarr/files/9597100/prowlarr.debug.txt)

2022-09-26 06:23 UTC, usnail commented
> 



> @Qstick cardigann is still puking on a redirect being returned after Flaresolverr solves it
> 
> ```
> 16:00:37.7|Warn|Cardigann|https://kp.m-team.cc/adult.php?search=Elvis&incldead=0&spstate=0&search_area=0&search_mode=0&sort=4&type=desc
> 
> [v0.4.6.1969] NzbDrone.Core.Indexers.Exceptions.IndexerException: Unexpected response status Redirect code from API request
> ```

some times,site always redirect to verify page even though has login done（login otherwhere）

2022-09-29 06:40 UTC, closed without merging