Fixed: (Orpheus) Add remaster title and year to release title
Prowlarr/Prowlarr pull request #1322
Opened 2023-01-12 22:10 UTC by mynameisbogdan

#### Database Migration
NO

2023-01-12 22:40 UTC, bakerboy448 commented
gotta update the orpheus tests too ;)

```
"The Beatles - Abbey Road (1969) [MP3 V2 (VBR)] [BD]" with a length of 51, but
"The Beatles - Abbey Road (1969) [2.0 Mix 2019] [MP3 V2 (VBR)] [BD]" has a length of 66, differs near "2.0" (index 33).
```

2023-01-13 03:22 UTC, Qstick commented
Wonder how well this format plays with Lidarr.. might need some tweaks to that parser.

2023-01-13 03:23 UTC, Qstick requested changes
Just the one nitpick, looks ok otherwise.

2023-01-13 03:23 UTC, Qstick commented on src/NzbDrone.Core/Indexers/Definitions/Orpheus.cs
> +                    GazelleInfo release = new GazelleInfo
Use `var` here as well like you did above?

2023-01-13 03:25 UTC, bakerboy448 commented
![image](https://user-images.githubusercontent.com/55419169/212230180-f665d73c-edf3-47e2-8be5-12ac4ce0c7ff.png)![image](https://user-images.githubusercontent.com/55419169/212230188-c93367fc-6528-46c8-8110-fec2c4e2253f.png)

2023-01-13 03:35 UTC, Qstick approved these changes

2023-01-13 03:41 UTC, merged