New: Add TorrentRssIndexer
Prowlarr/Prowlarr pull request #1710
Opened 2023-06-02 00:02 UTC by mynameisbogdan

#### Database Migration
NO

#### Description
`Torrent RSS Feed` was requested.

* Fixes #1101
* Fixes #248

2023-06-02 00:03 UTC, bakerboy448 commented
Towards
- https://github.com/Prowlarr/Prowlarr/issues/1101
- https://github.com/Prowlarr/Prowlarr/issues/248

2023-06-02 00:05 UTC, bakerboy448 commented on src/NzbDrone.Core/Indexers/Definitions/TorrentRss/TorrentRssIndexer.cs
> +        public override string Description => "";
```suggestion
        public override string Description => "Generic RSS Feed containing torrents. Requires X Y Z RSS attributes";
```

or see faq entry for attributes

where X Y Z are the min required rss attributes

2023-06-02 00:07 UTC, bakerboy448 commented on src/NzbDrone.Core/Indexers/Definitions/TorrentRss/TorrentRssIndexer.cs
> +        public override string Description => "";
we'll want to add the FAQ entry name as well whatever the header is named.

2023-06-02 04:35 UTC, Qstick commented on src/NzbDrone.Core/Indexers/Definitions/TorrentRss/TorrentRssIndexerSettings.cs
> +        [FieldDefinition(2, Type = FieldType.Number, Label = "Default Size", HelpText="Add a default size for feeds with missing sizes.", Unit = "MB", Advanced = true)]
```suggestion
        [FieldDefinition(3, Type = FieldType.Number, Label = "Default Size", HelpText="Add a default size for feeds with missing sizes.", Unit = "MB", Advanced = true)]
```

2023-06-02 04:37 UTC, Qstick commented on src/NzbDrone.Core/Indexers/Definitions/TorrentRss/TorrentRssSettingsDetector.cs
> +        /// <returns>Parsed Settings or <c>null</c></returns>
Purge this as we aren't maintaining summary tags as a code style choice

2023-06-02 15:12 UTC, bakerboy448 commented on src/NzbDrone.Core/Indexers/Definitions/TorrentRss/TorrentRssIndexer.cs
> +        public override string Description => "";
https://wiki.servarr.com/en/prowlarr/faq#can-i-add-any-generic-torrent-rss-feed

needs to be populated with the required attributes.

2023-06-03 00:23 UTC, ilike2burnthing commented on src/NzbDrone.Core/Indexers/Definitions/TorrentRss/TorrentRssSettingsDetector.cs
> +                throw new UnsupportedFeedException("Size of one more releases lower than {0}, feed must contain release content size.", ValidSizeThreshold.SizeSuffix());
```suggestion
                throw new UnsupportedFeedException("Size of one or more releases lower than {0}, feed must contain release content size.", ValidSizeThreshold.SizeSuffix());
```

2023-06-03 00:24 UTC, ilike2burnthing commented on src/NzbDrone.Core/Indexers/Definitions/TorrentRss/TorrentRssIndexerSettings.cs
> +        [FieldDefinition(1, Label = "Cookie", HelpText = "If you site requires a login cookie to access the rss, you'll have to retrieve it via a browser.")]
```suggestion
        [FieldDefinition(1, Label = "Cookie", HelpText = "If your site requires a login cookie to access the RSS, you'll have to retrieve it via a browser.")]
```

2023-06-03 00:26 UTC, ilike2burnthing requested changes
Back again with the vital suggested changes ;)

2023-06-04 20:50 UTC, bakerboy448 commented
Oooh that's beautiful 😭

2023-06-07 00:57 UTC, Qstick approved these changes

2023-06-07 00:57 UTC, merged