New: (Indexer) Shizaproject
Prowlarr/Prowlarr pull request #349
Opened 2021-07-14 02:33 UTC by dm3ch

#### Database Migration
NO

#### Description
Adding Shizaproject indexer support

#### Screenshot (if UI related)

#### Todos
- [ ] Tests
- [ ] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [ ] [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

* Fixes #XXXX

2021-07-14 02:51 UTC, Qstick requested changes
Just the one nitpick

2021-07-14 02:51 UTC, Qstick commented on src/NzbDrone.Core/Indexers/Definitions/Shizaproject.cs
> +        private IEnumerable<IndexerRequest> GetPagedRequests(string term, int[] categories, string imdb = null)
Ditch IMDb here if it’s never used

2021-07-14 02:54 UTC, dm3ch commented
@Qstick I have tested this indexer manually and found strange issue. Manual search works, but Sonarr search doesn't.
Maybe you have any ideas, before I would start deep debugging? :)

2021-07-14 02:56 UTC, dm3ch commented on src/NzbDrone.Core/Indexers/Definitions/Shizaproject.cs
> +        private IEnumerable<IndexerRequest> GetPagedRequests(string term, int[] categories, string imdb = null)
Deleted

2021-07-14 02:57 UTC, Qstick commented
Which categories is Sonarr using? Because only one is supported by this definition (TV Anime)

2021-07-14 02:58 UTC, dm3ch commented
> Which categories is Sonarr using? Because only one is supported by this definition (TV Anime)

I tried to enable all available categories on sonarr side but it didn't help me. :(

2021-07-14 02:59 UTC, Qstick commented
Jump on discord if you want to debug some, I’m not somewhere I can test the PR currently

2021-07-14 11:07 UTC, dm3ch commented
@Qstick I have found what caused this issue.

During manual search I have "search term", but during automatic query it was "search term S01".
So I added regexp to filter that before requesting API.

The most interesting - when I was looking Prowlarr requests history, request results was 0, when I pressed manual search button in history view I got results. So search button from history view generates different search term than original request. :)

2021-07-15 13:49 UTC, bakerboy448 commented
update when merged https://requests.prowlarr.com/b/feedback/p/torrent-shizaproject

2021-07-17 12:29 UTC, merged