Added lazylibrarian application sync
Prowlarr/Prowlarr pull request #453
Opened 2021-08-22 21:36 UTC by philborman

#### Database Migration
NO

#### Description
Adds lazylibrarian support to Prowlarr, list/add/delete/change providers

#### Todos
- [ ] Tests
- [ ] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [ ] [Wiki Updates](https://wiki.servarr.com)

2021-08-23 02:24 UTC, Qstick requested changes

2021-08-23 02:24 UTC, Qstick commented on LazyLibrarianField.cs
> +namespace NzbDrone.Core.Applications.LazyLibrarian
Purge this file, not used

2021-08-23 09:23 UTC, philborman commented
Sorry, just cloned the mylar code and tweaked it a bit. Uploaded changes.

2021-08-28 16:43 UTC, bakerboy448 commented
There's still many outstanding requested changes pending.

Refer to the mylar3 cleanup commit for some more info https://github.com/Prowlarr/Prowlarr/commit/c72222a696752f837bcbb6001f5aaa0c4c9fdb77

2021-08-28 17:02 UTC, philborman commented
All the changes are made here, looks like the file upload doesn't overwrite the earlier uploaded files.
I have attached new copies. If this doesn't work, can you delete the merge request and I will open a new one. Thanks,
[LazyLibrarian.zip](https://github.com/Prowlarr/Prowlarr/files/7071088/LazyLibrarian.zip)

2021-08-28 17:11 UTC, bakerboy448 commented
just make a commit with the changes for the files to the branch on your fork

https://docs.github.com/en/github/collaborating-with-pull-requests/getting-started/about-collaborative-development-models

2021-08-28 17:21 UTC, closed without merging