Fixed: Update from version in logs
Prowlarr/Prowlarr pull request #874
Opened 2022-03-04 19:34 UTC by bakerboy448

Closes #873

(cherry picked from commit bc3e3714b97dec19091e45324d9f2b550f1dbbd5)

#### Database Migration
NO

#### Description
A few sentences describing the overall goals of the pull request's commits.

#### Screenshot (if UI related)

#### Todos
- [ ] Tests
- [ ] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [ ] [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

* Fixes #XXXX

2022-03-07 03:22 UTC, Qstick commented on src/NzbDrone.Update/UpdateEngine/DetectExistingVersion.cs
> +                var targetExecutable = Path.Combine(targetFolder, BuildInfo.AppName.ProcessNameToExe());
Prowlarr.dll or BuildInfo.AppName + ".dll"

2022-03-07 03:22 UTC, Qstick requested changes
Bring it up to date

2022-03-24 02:17 UTC, Qstick commented
Original Author is dropped

2022-03-24 02:51 UTC, bakerboy448 commented
> Original Author is dropped

fixed

2022-03-24 23:50 UTC, Qstick commented
> > Original Author is dropped
> 
> fixed

Sure?

2022-03-25 23:56 UTC, Qstick commented
No fixy
![image](https://user-images.githubusercontent.com/376117/160215747-9b54e066-2456-4bf5-9325-aeff850ac67e.png)

2022-03-27 14:49 UTC, bakerboy448 commented
now fixy

2022-03-30 04:22 UTC, Qstick approved these changes

2022-03-30 04:23 UTC, merged