Fixed: No longer require first run as admin on windows
Prowlarr/Prowlarr pull request #885
Opened 2022-03-11 18:36 UTC by bakerboy448

(cherry picked from commit 8d9302da7761752189b2d2820915d7d13197ce47)
(cherry picked from commit daa9ee30a2c5fc2511e34167ce642c1bfe2a8b41)

#### Database Migration
NO

#### Description
A few sentences describing the overall goals of the pull request's commits.

#### Screenshot (if UI related)

#### Todos
- [ ] Tests
- [ ] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [ ] [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

* Fixes #XXXX

2022-03-21 22:59 UTC, Qstick requested changes

2022-03-21 22:59 UTC, Qstick commented on build.sh
> +        sed -i'' -e "s/<string>10.0.0.0<\/string>/<string>$PROWLARRVERSION<\/string>/g" macOS/Prowlarr.app/Contents/Info.plist
Keep this in distribution folder, this is the future structure, just haven’t changed the other repos

2022-03-21 22:59 UTC, Qstick commented on build.sh
> +    cp -r macOS/Prowlarr.app $folder
Same

2022-03-24 01:08 UTC, bakerboy448 commented
Can't figure out / see why the installer create is failing....

2022-03-24 01:25 UTC, bakerboy448 commented
> > Can't figure out / see why the installer create is failing....
> 
> Did you read the error?

yes... but don't see where in the the build script it is missing the piece or I suppose missing/typoed folder.

```
Creating output directory: D:\a\1\s\distribution\windows\setup\output
[...]
Error on line 55 in D:\a\1\s\distribution\windows\setup\prowlarr.iss: Source file "D:\a\1\s\distribution\windows\setup\..\_artifacts\win-x64\net6.0\Prowlarr\Prowlarr.exe" does not exist.
Compile aborted.
cp: cannot stat 'distribution/windows/setup/output/Prowlarr.*win-x64.exe': No such file or directory
cp: cannot stat 'distribution/windows/setup/output/Prowlarr.*win-x86.exe': No such file or directory
```

2022-03-24 01:32 UTC, Qstick commented
Baker: "We don't need this extra two levels"
![image](https://user-images.githubusercontent.com/376117/159824062-983ba4b7-435e-44e1-af8d-5e3dd3aef78e.png)

Azure: 
`Source file "D:\a\1\s\distribution\windows\setup\..\_artifacts\win-x64\net6.0\Prowlarr\Prowlarr.exe" does not exist.`

Baker: "Why won't you work" :D

Just fix those path references since we have the `distribution\windows` folder here in Prowlarr

2022-03-24 01:35 UTC, bakerboy448 commented
baker: doh

thx

2022-03-24 01:36 UTC, Qstick commented
np

2022-03-24 01:52 UTC, Qstick commented on azure-pipelines.yml
> +             yarn
purge this back out, it was removed to ensure no cross OS cache restore for yarn

2022-03-24 01:53 UTC, Qstick commented on azure-pipelines.yml
> +             yarn
and this

2022-03-24 01:58 UTC, merged